apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zq43rmv27-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:e8f4216bf41831416d223b180f1523dd90aa5a4f@sha256:a47aa65d851e63990651a0f4b5c13238545f008524541ddf3582ee8abb6349f2
          name: container-image
